Fix charmap windows error and add test examples
Genez-io/genezio-tests pull request #65
Opened 2024-02-22 12:30 UTC by cristim67

2024-02-22 12:59 UTC, costinsin requested changes

2024-02-22 12:59 UTC, costinsin commented on test_all_examples.py
> +	run.test_example_repo("typescript", "webhook", rootPath)
1. variables in python are `snake_case`
2. it's better to define an array of examples and then loop through them, than copy paste the function multiple times.

```suggestion
    root_path = os.getcwd()
    examples = [
        { language: "typescript", app: "crud-app" },
        { language: "typescript", app: "getting-started" },
        { language: "typescript", app: "hello-world" },
        { language: "typescript", app: "multiversx" },
        { language: "typescript", app: "quiz-app-prisma" },
        { language: "typescript", app: "shopping-cart" },
        { language: "typescript", app: "todo-list-angular" },
        { language: "typescript", app: "todo-list-flutter" },
        { language: "typescript", app: "todo-list" },
        { language: "typescript", app: "webhook" },
    ]

    for example in examples:
        run.test_example_repo(example.language, example.app, root_path)
```

2024-02-22 12:59 UTC, costinsin commented on test_example_repo.py
> +	test_example_repo("typescript", "webhook", os.getcwd())
Is this intended to only test `webhook`?

2024-02-22 12:59 UTC, costinsin commented on test_example_repo.py
> +	os.chdir(os.path.join(path, "projects", "examples", "genezio-examples", language, repoNameExample))
```suggestion
def test_example_repo(language: str, repo_name_example: str, path: str):
	print("Starting {} test...".format(language + " " + repo_name_example))
	token = os.environ.get('GENEZIO_TOKEN')

	os.chdir(os.path.join(path, "projects", "examples", "genezio-examples", language, repo_name_example))
```

2024-02-26 10:01 UTC, radu1122 commented on .gitmodules
> +	path = projects/examples/genezio-examples
here should be added an automatic flow to get all the time the latest updates from the genezio-examples

2024-02-26 10:04 UTC, costinsin approved these changes

2024-02-27 12:56 UTC, merged